module.exports = {
  MYSQL: false,

  // 网易云音乐api
  CLOUD_MUSIC_SUCCESS_STATUS: 200,
  // 二维码状态
  CLOUD_MUSIC_SCAN_EXPIRE_STATUS: 800,
  CLOUD_MUSIC_SCAN_WAIT_STATUS: 801,
  CLOUD_MUSIC_AUTH_WAIT_STATUS: 802,
  CLOUD_MUSIC_SCAN_FINISHED_STATUS: 803,
};
